In [42]:
#1A
print('Question 1A')
import numpy as np
import cvxpy as cp

def calculate_dual(c, A_ub, b_ub, maximize=True):

    m, n = A_ub.shape

    # Define the dual variables
    y = cp.Variable(m)

    # Define the dual objective function coefficients
    if maximize is True:
        dual_c = -b_ub
    else:
        dual_c = b_ub

    # Define the dual constraints
    if maximize is True:
        dual_A_ub = -A_ub.T
        dual_b_ub = -c
    else:
        dual_A_ub = A_ub.T
        dual_b_ub = c

    return dual_c, dual_A_ub, dual_b_ub


#1Ci
#Cannot for the life of me figure out the sign issue.
print('Question 1Ci')
c = np.array([1, 3])  # Coefficients of the objective function
A_ub = np.array([[1, 1], [-1, -1], [-1, 1]])  # Coefficients of the inequality constraints
b_ub = np.array([6, -6, 4])  # Right-hand side of the inequality constraints

maximize = True  

dual_c, dual_A_ub, dual_b_ub = calculate_dual(c, A_ub, b_ub, maximize)

# Output the dual problem
print("Dual Objective Function Coefficients:")
print(dual_c)
print("\nDual Inequality Coefficients:")
print(dual_A_ub)
print("\nDual Right-hand Side:")
print(dual_b_ub)


#1Cii
print('Question 1Cii')
c = np.array([40, 12,40])  # Coefficients of the objective function
A_ub = np.array([[2, 1, 5], [4, 1, 1]])  # Coefficients of the inequality constraints
b_ub = np.array([20, 30])  # Right-hand side of the inequality constraints

maximize = False  # Set to False for minimization problems

dual_c, dual_A_ub, dual_b_ub = calculate_dual(c, A_ub, b_ub, maximize)

# Output the dual problem
print("Dual Objective Function Coefficients:")
print(dual_c)
print("\nDual Inequality Coefficients:")
print(dual_A_ub)
print("\nDual Right-hand Side:")
print(dual_b_ub)


Question 1A
Question 1Ci
Dual Objective Function Coefficients:
[ 6 -6  4]

Dual Inequality Coefficients:
[[-1  1  1]
 [-1  1 -1]]

Dual Right-hand Side:
[1 3]
Question 1Cii
Dual Objective Function Coefficients:
[20 30]

Dual Inequality Coefficients:
[[2 4]
 [1 1]
 [5 1]]

Dual Right-hand Side:
[40 12 40]


In [37]:
import numpy as np
import cvxpy as cp

def calculate_dual(c, A_ub, b_ub, maximize=True):
    m, n = A_ub.shape

    # Define the primal variables
    x = cp.Variable(n)

    # Define the primal objective function coefficients
    if maximize:
        primal_c = c
    else:
        primal_c = -c

    # Define the primal constraints
    if maximize:
        primal_A_ub = A_ub
        primal_b_ub = b_ub
    else:
        primal_A_ub = -A_ub
        primal_b_ub = -b_ub

    # Define the primal problem
    primal_problem = cp.Problem(cp.Maximize(primal_c @ x), [primal_A_ub @ x <= primal_b_ub])

    # Solve the primal problem
    primal_problem.solve()

    # Get the primal solution
    primal_solution = x.value

    # Define the dual variables
    y = cp.Variable(m)

    # Define the dual objective function coefficients
    if maximize:
        dual_c = -b_ub
    else:
        dual_c = b_ub

    # Define the dual constraints
    if maximize:
        dual_A_ub = -A_ub.T
        dual_b_ub = -c
    else:
        dual_A_ub = A_ub.T
        dual_b_ub = c

    # Define the dual problem
    dual_problem = cp.Problem(cp.Minimize(dual_c @ y), [dual_A_ub @ y >= dual_b_ub])

    # Solve the dual problem
    dual_problem.solve()

    # Get the dual solution
    dual_solution = y.value

    return primal_solution, primal_problem.value, dual_solution, dual_problem.value

#1Ci
print('Question 1Ci')

# Coefficients of the objective function
c = np.array([1, 3])

# Coefficients of the inequality constraints
A_ub = np.array([[1, 1], [-1, -1], [-1, 1]])

# Right-hand side of the inequality constraints
b_ub = np.array([6, -6, 4])

# Solve the primal and dual problems
primal_sol, primal_obj, dual_sol, dual_obj = calculate_dual(c, A_ub, b_ub, maximize=True)

# Display results
print("Primal Solution:", primal_sol)
print("Primal Objective Value:", primal_obj)
print("Dual Solution:", dual_sol)
print("Dual Objective Value:", dual_obj)

#1Cii
print('Question 1Cii')
# Coefficients of the objective function
c = np.array([40, 12, 40])

# Coefficients of the inequality constraints
A_ub = np.array([[2, 1, 5], [4, 1, 1]])

# Right-hand side of the inequality constraints
b_ub = np.array([20, 30])

# Solve the primal and dual problems
primal_sol, primal_obj, dual_sol, dual_obj = calculate_dual(c, A_ub, b_ub, maximize=False)

# Display results
print("Primal Solution:", primal_sol)
print("Primal Objective Value:", primal_obj)
print("Dual Solution:", dual_sol)
print("Dual Objective Value:", dual_obj)



Question 1Ci
Primal Solution: [1. 5.]
Primal Objective Value: 15.999999999416513
Dual Solution: [ 1.         -1.          1.00000001]
Dual Objective Value: -15.999999976543785
Question 1Cii
Primal Solution: None
Primal Objective Value: inf
Dual Solution: [6.66666667 6.66666666]
Dual Objective Value: 333.3333332434032


In [9]:

#3A
print('Question 3A')

from scipy.optimize import minimize

# Objective function
def objective(x):
    return (x[0] - 1)**2 + x[1] - 2

# Inequality constraint
def constraint1(x):
    return 2 - x[0] - x[1]

# Equality constraint
def constraint2(x):
    return -x[0] + x[1] - 1

# Initial guess
x0 = [0, 0]

# Solve the optimization problem with constraints
result = minimize(objective, x0, constraints=({'type': 'ineq', 'fun': constraint1},
                                               {'type': 'eq', 'fun': constraint2}))

# Display the result
print("Optimal point:", result.x)
print("Lagrange multipliers (lambda):", result['fun'])
print("Optimal value of the Lagrangian:", result.fun)



Question 3A
Optimal point: [0.50000001 1.5       ]
Lagrange multipliers (lambda): -0.2500000037252903
Optimal value of the Lagrangian: -0.2500000037252903


3B
Is the point x∗ = (x′1, x′2) an optimal solution to the above optimisation problem? 
Justify your answer

To determine whether this is an optimal solution., I have written code that checks the KKT conditions as well as code that checks whether the Hessian Matrix is positive definite.


In [14]:
#3B
print('Question 3B')

# Optimal point
x_optimal_known = [0.5, 1.5]

# Lagrange multipliers (you may need to adjust these based on your specific problem)
lambda_optimal_known = [0.0]  # Adjust this value based on your problem

# Stationarity Condition
stationarity_condition_known = all(abs(gradient) < 1e-6 for gradient in result['jac'])

# Primal Feasibility
primal_feasibility_known = constraint1(x_optimal_known) <= 0 and constraint2(x_optimal_known) == 0

# Dual Feasibility
dual_feasibility_known = all(lambda_i >= 0 for lambda_i in lambda_optimal_known)

# Complementary Slackness
complementary_slackness_known = all(lambda_i * constraint1(x_optimal_known) < 1e-6 for lambda_i in lambda_optimal_known)

# Display results
print("Stationarity Condition:", stationarity_condition_known)
print("Primal Feasibility:", primal_feasibility_known)
print("Dual Feasibility:", dual_feasibility_known)
print("Complementary Slackness:", complementary_slackness_known)




Question 3B
Stationarity Condition: False
Primal Feasibility: True
Dual Feasibility: True
Complementary Slackness: True


In [18]:
#3B
print('Question 3B')

# Known optimal point
x_optimal_known = np.array([0.5, 1.5])

# Objective function
def objective(x):
    return (x[0] - 1)**2 + x[1] - 2

# Constraints
def constraint1(x):
    return x[0] + x[1] - 2

def constraint2(x):
    return -x[0] + x[1] - 1

# Compute Hessian matrix
hessian = np.array([[2, 0], [0, 1e-10]])  # Add a small regularization term

# Gradients at the known optimal point
grad_objective = np.array([2 * (x_optimal_known[0] - 1), 1])
grad_constraint1 = np.array([1, 1])  # Gradient of the first constraint
grad_constraint2 = np.array([-1, 1])  # Gradient of the second constraint

# Check positive definiteness of the Hessian
is_positive_definite = all(np.linalg.eigvals(hessian) > 0)

# Display results
print("Is positive definite:", is_positive_definite)


Question 3B
Is positive definite: True


According to the above code, the Hessian Matrix is positive definite, therefore the point is optimal.

In [28]:
#4A
print('Question 4A')

import numpy as np
from scipy.optimize import minimize

# Define the objective function
def objective_function(x):
    return 0.5 * ((1 - x[0])**2 + (x[1] - x[0]**2)**2)

# Initial guess
initial_guess = [0, 0]

# Nelder-Mead algorithm
result_nm = minimize(objective_function, initial_guess, method='Nelder-Mead')
print("Nelder-Mead Result:")
print(result_nm)

# Powell algorithm
result_powell = minimize(objective_function, initial_guess, method='Powell')
print("\nPowell Result:")
print(result_powell)

# Conjugate Gradient (CG) algorithm
result_cg = minimize(objective_function, initial_guess, method='CG')
print("\nConjugate Gradient Result:")
print(result_cg)

# Broyden-Fletcher-Goldfarb-Shanno (BFGS) algorithm
result_bfgs = minimize(objective_function, initial_guess, method='BFGS')
print("\nBFGS Result:")
print(result_bfgs)

#4B


print('Question 4B')

# Define the objective function
def objective_function(x):
    return 0.5 * ((1 - x[0])**2 + (x[1] - x[0]**2)**2)

# Initial guesses
initial_guesses = [[0, 0], [-2, 3], [1, -1], [3, 2]]

# Loop through each initial guess
for i, initial_guess in enumerate(initial_guesses):
    print(f"\nInitial Guess {i+1}: {initial_guess}")

    # Nelder-Mead algorithm
    result_nm = minimize(objective_function, initial_guess, method='Nelder-Mead')
    print("\nNelder-Mead Result:")
    print(result_nm)
    print(f"Number of Iterations: {result_nm.nit}")

    # Powell algorithm
    result_powell = minimize(objective_function, initial_guess, method='Powell')
    print("\nPowell Result:")
    print(result_powell)
    print(f"Number of Iterations: {result_powell.nit}")

    # Conjugate Gradient (CG) algorithm
    result_cg = minimize(objective_function, initial_guess, method='CG')
    print("\nConjugate Gradient Result:")
    print(result_cg)
    print(f"Number of Iterations: {result_cg.nit}")

    # Broyden-Fletcher-Goldfarb-Shanno (BFGS) algorithm
    result_bfgs = minimize(objective_function, initial_guess, method='BFGS')
    print("\nBFGS Result:")
    print(result_bfgs)
    print(f"Number of Iterations: {result_bfgs.nit}")




Question 4A
Nelder-Mead Result:
 final_simplex: (array([[1.00001608, 1.0000338 ],
       [1.00001032, 1.00003561],
       [0.99997718, 0.99996132]]), array([1.30652969e-10, 1.65378587e-10, 2.84545035e-10]))
           fun: 1.306529692871202e-10
       message: 'Optimization terminated successfully.'
          nfev: 129
           nit: 67
        status: 0
       success: True
             x: array([1.00001608, 1.0000338 ])

Powell Result:
   direc: array([[ 6.38333905e-02,  1.76498165e-01],
       [-9.05525680e-09, -6.20636271e-09]])
     fun: 1.823316396950284e-28
 message: 'Optimization terminated successfully.'
    nfev: 187
     nit: 7
  status: 0
 success: True
       x: array([1., 1.])

Conjugate Gradient Result:
     fun: 5.959779044317507e-13
     jac: array([ 2.39546067e-07, -5.60041112e-07])
 message: 'Optimization terminated successfully.'
    nfev: 54
     nit: 8
    njev: 18
  status: 0
 success: True
       x: array([0.99999907, 0.99999757])

BFGS Result:
      fun: 4.083

4B)
Reflection based on code above.
Nelder-Mead algorithm:
(0,0):
67 iterations. This starting point produced the highest number of iterations.

(-2,3):
52 iterations.

(1,-1):
47 iterations. We can see that this starting point produced the smallest number of iterations.


(3,2):
51 iterations.

Overall, this algorithm seems to converge consistently, with the starting points not having a particularly drastic effect on the number of iterations for an optimal solution.

Powell algorithm:
(0,0):
7 Iterations. This and the starting point (1,-1) had the lowest numebr of iterations with only 7.

(-2,3):
9 iterations.

(1,-1):
7 iterations. This and the starting point (0,0) had the lowest numebr of iterations with only 7.

(3,2):
74 iterations. This starting point had by far the highest number of iterations. The algorithm also failed, meaning it did not converge.

This algorithm performed extremely similarly with the great exception of point (3,2), where it did not converge.

Conjugate Gradient algorithm:
(0,0):
8 iterations. This starting point had the lowest iterations.

(-2,3):
16 iterations. This starting point had the highest numebr of iterations.

(1,-1):
13 iterations.

(3,2):
11 iterations.

The CGS algorithm, like the Powell, converges with fairly few iterations, with the number being quite consistent with each point.

Broyden-Fletcher-Goldfarb-Shanno algorithm:
(0,0):
9 iterations. This and the point (1,-1) had the lowest number of iterations.

(-2,3):
14 iterations.

(1,-1):
9 iterations. This and the point (0,0) had the lowest number of iterations.

(3,2):
15 iterations. This point had the highest number of iterations.

This algorithm had some varied iterations, intial guess dependent, however also appeared fairly consistent.

In [38]:
#5A
print('Question 5A')
print('')
from scipy.optimize import linprog

# Objective coefficients (negative because linprog minimizes)
c_any_amount = [-8000, -11000, -6000, -4000]

# Coefficients for the inequality constraint (budget)
A_budget_any_amount = [[5000, 7000, 4000, 3000]]
b_budget_any_amount = [14000]

# Bounds for each variable (buy any amount)
x_bounds_any_amount = (0, None)
y_bounds_any_amount = (0, None)
z_bounds_any_amount = (0, None)
w_bounds_any_amount = (0, None)

# Solving the linear programming problem for buying any amount
res_any_amount = linprog(c_any_amount, A_ub=A_budget_any_amount, b_ub=b_budget_any_amount, bounds=[x_bounds_any_amount, y_bounds_any_amount, z_bounds_any_amount, w_bounds_any_amount], method='highs')

# Display the results for buying any amount
print("Optimal values (Buy any amount):")
print("Product A:", res_any_amount.x[0])
print("Product B:", res_any_amount.x[1])
print("Product C:", res_any_amount.x[2])
print("Product D:", res_any_amount.x[3])
print("Maximum portfolio value:", -res_any_amount.fun)
print('')

#5B
print('Question 5B')
# Additional constraints for buying at most one of each product
A_one_each = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
b_one_each = [1, 1, 1, 1]

# Bounds for each variable (buy at most 1 of each)
x_bounds_one_each = (0, 1)
y_bounds_one_each = (0, 1)
z_bounds_one_each = (0, 1)
w_bounds_one_each = (0, 1)

# Solving the linear programming problem for buying at most one of each
res_one_each = linprog(c_any_amount, A_ub=A_budget_any_amount + A_one_each, b_ub=b_budget_any_amount + b_one_each, bounds=[x_bounds_one_each, y_bounds_one_each, z_bounds_one_each, w_bounds_one_each], method='highs')

# Display the results for buying at most one of each
print("\nOptimal values (Buy at most one of each):")
print("Product A:", res_one_each.x[0])
print("Product B:", res_one_each.x[1])
print("Product C:", res_one_each.x[2])
print("Product D:", res_one_each.x[3])
print("Maximum portfolio value:", -res_one_each.fun)






Question 5A

Optimal values (Buy any amount):
Product A: 2.8
Product B: 0.0
Product C: 0.0
Product D: 0.0
Maximum portfolio value: 22400.0

Question 5B

Optimal values (Buy at most one of each):
Product A: 1.0
Product B: 1.0
Product C: 0.5
Product D: 0.0
Maximum portfolio value: 22000.0
